import type { SourceDraft } from '@/types/source';

export type SourceStatus = 'active' | 'worker_ready';
export type SourceCategory = 'portal' | 'marketplace' | 'room' | 'agency' | 'public_housing' | 'student' | 'furnished';
export type SourceMarket = 'DE';
export type WorkerStrategy = 'auto' | 'official_api' | 'public_html' | 'rss';

export interface SourceCatalogEntry {
  id: string;
  label: string;
  market: SourceMarket;
  country: string;
  defaultCity: string;
  defaultListingType: SourceDraft['listingType'];
  defaultMaxResults: string;
  executionMode: SourceDraft['executionMode'];
  workerPath: string;
  description: string;
  category: SourceCategory;
  status: SourceStatus;
  cities: string[];
  supportsDemo: boolean;
  supportsWorker: boolean;
  enabledByDefault: boolean;
  workerStrategyHint: WorkerStrategy;
  defaultConfig: Record<string, string>;
  docsUrl?: string;
}

function entry(input: Omit<SourceCatalogEntry, 'market' | 'country' | 'defaultCity' | 'cities'> & { country?: string; defaultCity?: string; cities?: string[] }) : SourceCatalogEntry {
  return {
    market: 'DE',
    country: input.country ?? 'DE',
    defaultCity: input.defaultCity ?? 'Berlin',
    cities: input.cities ?? ['Berlin'],
    ...input,
  };
}

export const sourceCatalog: SourceCatalogEntry[] = [
  entry({
    id: 'immoscout-de',
    label: 'ImmobilienScout24',
    defaultListingType: 'rent',
    defaultMaxResults: '40',
    executionMode: 'auto',
    workerPath: '/sources/fetch',
    description: 'Largest Berlin property portal in the app. Uses the official partner API when credentials exist, otherwise falls back to public search-page parsing.',
    category: 'portal',
    status: 'active',
    supportsDemo: true,
    supportsWorker: true,
    enabledByDefault: true,
    workerStrategyHint: 'auto',
    defaultConfig: {
      fetchStrategy: 'auto',
      includeHouses: 'yes',
      district: '',
      customSearchUrl: 'https://www.immobilienscout24.de/Suche/de/berlin/berlin/wohnung-mieten',
    },
    docsUrl: 'https://api.immobilienscout24.de/api-docs/search/introduction/',
  }),
  entry({
    id: 'immowelt-de',
    label: 'Immowelt',
    defaultListingType: 'rent',
    defaultMaxResults: '35',
    executionMode: 'auto',
    workerPath: '/sources/fetch',
    description: 'Major Berlin search portal with public result pages for rent and buy inventory.',
    category: 'portal',
    status: 'active',
    supportsDemo: true,
    supportsWorker: true,
    enabledByDefault: true,
    workerStrategyHint: 'public_html',
    defaultConfig: {
      fetchStrategy: 'public_html',
      includeHouses: 'yes',
      district: '',
      customSearchUrl: 'https://www.immowelt.de/suche/mieten/wohnung/berlin/berlin-10115/ad08de8634',
    },
    docsUrl: 'https://www.immowelt.de/',
  }),
  entry({
    id: 'immonet-de',
    label: 'Immonet',
    defaultListingType: 'rent',
    defaultMaxResults: '35',
    executionMode: 'auto',
    workerPath: '/sources/fetch',
    description: 'Berlin overlap portal that often mirrors and supplements mainstream listings.',
    category: 'portal',
    status: 'active',
    supportsDemo: true,
    supportsWorker: true,
    enabledByDefault: true,
    workerStrategyHint: 'public_html',
    defaultConfig: {
      fetchStrategy: 'public_html',
      includeHouses: 'yes',
      district: '',
      customSearchUrl: 'https://www.immonet.de/berlin/wohnung-mieten.html',
    },
    docsUrl: 'https://www.immonet.de/',
  }),
  entry({
    id: 'wg-gesucht-de',
    label: 'WG-Gesucht',
    defaultListingType: 'rent',
    defaultMaxResults: '30',
    executionMode: 'auto',
    workerPath: '/sources/fetch',
    description: 'Core Berlin source for shared flats, sublets, student rooms, and room-first inventory.',
    category: 'room',
    status: 'active',
    supportsDemo: true,
    supportsWorker: true,
    enabledByDefault: true,
    workerStrategyHint: 'public_html',
    defaultConfig: {
      fetchStrategy: 'public_html',
      wgMode: 'both',
      district: '',
      customSearchUrl: '',
    },
    docsUrl: 'https://www.wg-gesucht.de/',
  }),
  entry({
    id: 'ebay-kleinanzeigen-de',
    label: 'Kleinanzeigen',
    defaultListingType: 'rent',
    defaultMaxResults: '25',
    executionMode: 'auto',
    workerPath: '/sources/fetch',
    description: 'Marketplace-style Berlin listings from private landlords and informal supply.',
    category: 'marketplace',
    status: 'active',
    supportsDemo: true,
    supportsWorker: true,
    enabledByDefault: true,
    workerStrategyHint: 'public_html',
    defaultConfig: {
      fetchStrategy: 'public_html',
      district: '',
      customSearchUrl: 'https://www.kleinanzeigen.de/s-wohnungmieten/berlin/c203l3331',
    },
    docsUrl: 'https://www.kleinanzeigen.de/',
  }),
  entry({
    id: 'wohnungsboerse-de',
    label: 'Wohnungsboerse',
    defaultListingType: 'rent',
    defaultMaxResults: '20',
    executionMode: 'auto',
    workerPath: '/sources/fetch',
    description: 'Long-tail Berlin portal with supplemental apartment and studio inventory.',
    category: 'portal',
    status: 'active',
    supportsDemo: true,
    supportsWorker: true,
    enabledByDefault: false,
    workerStrategyHint: 'public_html',
    defaultConfig: {
      fetchStrategy: 'public_html',
      includeHouses: 'no',
      district: '',
      customSearchUrl: 'https://www.wohnungsboerse.net/Berlin/mieten/wohnungen',
    },
    docsUrl: 'https://www.wohnungsboerse.net/',
  }),
  entry({
    id: 'inberlinwohnen-de',
    label: 'inberlinwohnen',
    defaultListingType: 'rent',
    defaultMaxResults: '30',
    executionMode: 'auto',
    workerPath: '/sources/fetch',
    description: 'Joint portal for Berlin public housing companies and one of the best Berlin-specific affordable housing pages.',
    category: 'public_housing',
    status: 'active',
    supportsDemo: true,
    supportsWorker: true,
    enabledByDefault: true,
    workerStrategyHint: 'public_html',
    defaultConfig: {
      fetchStrategy: 'public_html',
      district: '',
      customSearchUrl: 'https://inberlinwohnen.de/wohnungsfinder/',
    },
    docsUrl: 'https://inberlinwohnen.de/wohnungsfinder/',
  }),
  entry({
    id: 'degewo-de',
    label: 'degewo',
    defaultListingType: 'rent',
    defaultMaxResults: '20',
    executionMode: 'auto',
    workerPath: '/sources/fetch',
    description: 'Berlin public-housing company search page for direct municipal inventory and alerts.',
    category: 'public_housing',
    status: 'active',
    supportsDemo: true,
    supportsWorker: true,
    enabledByDefault: false,
    workerStrategyHint: 'public_html',
    defaultConfig: {
      fetchStrategy: 'public_html',
      district: '',
      customSearchUrl: 'https://www.degewo.de/immosuche/',
    },
    docsUrl: 'https://www.degewo.de/immosuche/',
  }),
  entry({
    id: 'gesobau-de',
    label: 'GESOBAU',
    defaultListingType: 'rent',
    defaultMaxResults: '20',
    executionMode: 'auto',
    workerPath: '/sources/fetch',
    description: 'Direct public-housing offers from GESOBAU, including standard flats and some special housing formats.',
    category: 'public_housing',
    status: 'active',
    supportsDemo: true,
    supportsWorker: true,
    enabledByDefault: false,
    workerStrategyHint: 'public_html',
    defaultConfig: {
      fetchStrategy: 'public_html',
      district: '',
      customSearchUrl: 'https://www.gesobau.de/mieten/wohnungssuche/',
    },
    docsUrl: 'https://www.gesobau.de/mieten/wohnungssuche/',
  }),
  entry({
    id: 'howoge-de',
    label: 'HOWOGE',
    defaultListingType: 'rent',
    defaultMaxResults: '20',
    executionMode: 'auto',
    workerPath: '/sources/fetch',
    description: 'HOWOGE apartment search for Berlin municipal inventory, often with WBS and new-build offers.',
    category: 'public_housing',
    status: 'active',
    supportsDemo: true,
    supportsWorker: true,
    enabledByDefault: false,
    workerStrategyHint: 'public_html',
    defaultConfig: {
      fetchStrategy: 'public_html',
      district: '',
      customSearchUrl: 'https://www.howoge.de/immobiliensuche/wohnungssuche.html',
    },
    docsUrl: 'https://www.howoge.de/immobiliensuche/wohnungssuche.html',
  }),
  entry({
    id: 'stadtundland-de',
    label: 'STADT UND LAND',
    defaultListingType: 'rent',
    defaultMaxResults: '20',
    executionMode: 'auto',
    workerPath: '/sources/fetch',
    description: 'Municipal Berlin inventory from STADT UND LAND, including visible new-build search pages.',
    category: 'public_housing',
    status: 'active',
    supportsDemo: true,
    supportsWorker: true,
    enabledByDefault: false,
    workerStrategyHint: 'public_html',
    defaultConfig: {
      fetchStrategy: 'public_html',
      district: '',
      customSearchUrl: 'https://stadtundland.de/wohnungssuche',
    },
    docsUrl: 'https://stadtundland.de/wohnungssuche',
  }),
  entry({
    id: 'wbm-de',
    label: 'WBM',
    defaultListingType: 'rent',
    defaultMaxResults: '20',
    executionMode: 'auto',
    workerPath: '/sources/fetch',
    description: 'WBM apartment offers with strong presence inside the S-Bahn ring and public listings pages.',
    category: 'public_housing',
    status: 'active',
    supportsDemo: true,
    supportsWorker: true,
    enabledByDefault: false,
    workerStrategyHint: 'public_html',
    defaultConfig: {
      fetchStrategy: 'public_html',
      district: '',
      customSearchUrl: 'https://www.wbm.de/wohnungen-berlin/angebote/',
    },
    docsUrl: 'https://www.wbm.de/wohnungen-berlin/angebote/',
  }),
  entry({
    id: 'gewobag-de',
    label: 'Gewobag',
    defaultListingType: 'rent',
    defaultMaxResults: '20',
    executionMode: 'auto',
    workerPath: '/sources/fetch',
    description: 'Gewobag search and offer pages for public-housing inventory in Berlin.',
    category: 'public_housing',
    status: 'worker_ready',
    supportsDemo: true,
    supportsWorker: true,
    enabledByDefault: false,
    workerStrategyHint: 'public_html',
    defaultConfig: {
      fetchStrategy: 'public_html',
      district: '',
      customSearchUrl: 'https://www.gewobag.de/fuer-mietinteressentinnen/wohnungssuche/',
    },
    docsUrl: 'https://www.gewobag.de/fuer-mietinteressentinnen/wohnungssuche/',
  }),
  entry({
    id: 'berlinovo-de',
    label: 'berlinovo Apartments',
    defaultListingType: 'rent',
    defaultMaxResults: '18',
    executionMode: 'auto',
    workerPath: '/sources/fetch',
    description: 'Berlinovo apartment portal for furnished and temporary apartments across Berlin.',
    category: 'furnished',
    status: 'worker_ready',
    supportsDemo: true,
    supportsWorker: true,
    enabledByDefault: false,
    workerStrategyHint: 'public_html',
    defaultConfig: {
      fetchStrategy: 'public_html',
      district: '',
      customSearchUrl: 'https://www.backend.berlinovo.de/de/apartments/apartmentanlagen',
    },
    docsUrl: 'https://www.backend.berlinovo.de/de/apartments/apartmentanlagen',
  }),
  entry({
    id: 'bgg-berlin-student-de',
    label: 'BGG Berlinovo Studentenapartments',
    defaultListingType: 'rent',
    defaultMaxResults: '15',
    executionMode: 'auto',
    workerPath: '/sources/fetch',
    description: 'Berlinovo-related student apartment projects and trainee/student inventory pages.',
    category: 'student',
    status: 'worker_ready',
    supportsDemo: true,
    supportsWorker: true,
    enabledByDefault: false,
    workerStrategyHint: 'public_html',
    defaultConfig: {
      fetchStrategy: 'public_html',
      district: '',
      customSearchUrl: 'https://www.bgg-berlin.com/de/vermietung/apartmentanlagen',
    },
    docsUrl: 'https://www.bgg-berlin.com/de/vermietung/apartmentanlagen',
  }),
  entry({
    id: 'studierendenwerk-berlin-de',
    label: 'studierendenWERK BERLIN',
    defaultListingType: 'rent',
    defaultMaxResults: '12',
    executionMode: 'auto',
    workerPath: '/sources/fetch',
    description: 'Student housing overview and application portal for Berlin dormitories and residence halls.',
    category: 'student',
    status: 'worker_ready',
    supportsDemo: true,
    supportsWorker: true,
    enabledByDefault: false,
    workerStrategyHint: 'public_html',
    defaultConfig: {
      fetchStrategy: 'public_html',
      district: '',
      customSearchUrl: 'https://www.stw.berlin/en/housing/',
    },
    docsUrl: 'https://www.stw.berlin/en/housing/',
  }),
  entry({
    id: 'studentendorf-berlin-de',
    label: 'Studentendorf Berlin',
    defaultListingType: 'rent',
    defaultMaxResults: '12',
    executionMode: 'auto',
    workerPath: '/sources/fetch',
    description: 'Student room and flat-share inventory from the Berlin student village operators.',
    category: 'student',
    status: 'active',
    supportsDemo: true,
    supportsWorker: true,
    enabledByDefault: false,
    workerStrategyHint: 'public_html',
    defaultConfig: {
      fetchStrategy: 'public_html',
      district: '',
      customSearchUrl: 'https://www.studentendorf.berlin/de/wg-zimmer/',
    },
    docsUrl: 'https://www.studentendorf.berlin/de/wg-zimmer/',
  }),
  entry({
    id: 'wunderflats-berlin-de',
    label: 'Wunderflats',
    defaultListingType: 'rent',
    defaultMaxResults: '25',
    executionMode: 'auto',
    workerPath: '/sources/fetch',
    description: 'Large furnished and temporary-housing portal with a dedicated Berlin inventory page.',
    category: 'furnished',
    status: 'active',
    supportsDemo: true,
    supportsWorker: true,
    enabledByDefault: false,
    workerStrategyHint: 'public_html',
    defaultConfig: {
      fetchStrategy: 'public_html',
      district: '',
      customSearchUrl: 'https://wunderflats.com/en/furnished-apartments/berlin',
    },
    docsUrl: 'https://wunderflats.com/en/furnished-apartments/berlin',
  }),
  entry({
    id: 'housinganywhere-berlin-de',
    label: 'HousingAnywhere',
    defaultListingType: 'rent',
    defaultMaxResults: '25',
    executionMode: 'auto',
    workerPath: '/sources/fetch',
    description: 'Berlin monthly-rental and student-friendly platform with rooms, studios, and apartments.',
    category: 'furnished',
    status: 'active',
    supportsDemo: true,
    supportsWorker: true,
    enabledByDefault: false,
    workerStrategyHint: 'public_html',
    defaultConfig: {
      fetchStrategy: 'public_html',
      district: '',
      customSearchUrl: 'https://housinganywhere.com/s/Berlin--Germany',
    },
    docsUrl: 'https://housinganywhere.com/s/Berlin--Germany',
  }),
  entry({
    id: 'spotahome-berlin-de',
    label: 'Spotahome',
    defaultListingType: 'rent',
    defaultMaxResults: '25',
    executionMode: 'auto',
    workerPath: '/sources/fetch',
    description: 'Berlin furnished and medium-term rental platform with rooms, studios, and apartments.',
    category: 'furnished',
    status: 'active',
    supportsDemo: true,
    supportsWorker: true,
    enabledByDefault: false,
    workerStrategyHint: 'public_html',
    defaultConfig: {
      fetchStrategy: 'public_html',
      district: '',
      customSearchUrl: 'https://www.spotahome.com/de/s/berlin',
    },
    docsUrl: 'https://www.spotahome.com/de/s/berlin',
  }),
  entry({
    id: 'coming-home-berlin-de',
    label: 'coming home',
    defaultListingType: 'rent',
    defaultMaxResults: '18',
    executionMode: 'auto',
    workerPath: '/sources/fetch',
    description: 'Berlin-based furnished-apartment agency focused on temporary stays and premium local support.',
    category: 'furnished',
    status: 'worker_ready',
    supportsDemo: true,
    supportsWorker: true,
    enabledByDefault: false,
    workerStrategyHint: 'public_html',
    defaultConfig: {
      fetchStrategy: 'public_html',
      district: '',
      customSearchUrl: 'https://www.coming-home.com/mieten',
    },
    docsUrl: 'https://www.coming-home.com/mieten',
  }),
  entry({
    id: 'urbanbnb-berlin-de',
    label: 'Urbanbnb',
    defaultListingType: 'rent',
    defaultMaxResults: '18',
    executionMode: 'auto',
    workerPath: '/sources/fetch',
    description: 'Temporary Berlin rooms and furnished apartments with month-plus stays.',
    category: 'furnished',
    status: 'worker_ready',
    supportsDemo: true,
    supportsWorker: true,
    enabledByDefault: false,
    workerStrategyHint: 'public_html',
    defaultConfig: {
      fetchStrategy: 'public_html',
      district: '',
      customSearchUrl: 'https://www.urbanbnb.de/page/de/wohnen-auf-zeit-berlin?lang=de',
    },
    docsUrl: 'https://www.urbanbnb.de/page/de/wohnen-auf-zeit-berlin?lang=de',
  }),
  entry({
    id: 'local-agency-rss-de',
    label: 'Local Agency RSS',
    defaultListingType: 'rent',
    defaultMaxResults: '20',
    executionMode: 'auto',
    workerPath: '/sources/fetch',
    description: 'Neighborhood broker or agency feed for Berlin micro-market inventory. Configure one or more RSS/Atom URLs.',
    category: 'agency',
    status: 'worker_ready',
    supportsDemo: true,
    supportsWorker: true,
    enabledByDefault: true,
    workerStrategyHint: 'rss',
    defaultConfig: {
      fetchStrategy: 'rss',
      rssUrl: '',
      district: '',
    },
    docsUrl: 'https://inberlinwohnen.de/wohnungsfinder/',
  }),
];

export const adapterCatalog = sourceCatalog.map((item) => ({
  id: item.id,
  label: item.label,
  defaultCity: item.defaultCity,
}));

export function getSourceCatalogEntry(adapterId: string) {
  return sourceCatalog.find((item) => item.id === adapterId);
}

export function buildDraftFromCatalog(adapterId: string): SourceDraft {
  const entry = getSourceCatalogEntry(adapterId) ?? sourceCatalog[0]!;
  return {
    name: `${entry.label} ${entry.defaultCity}`,
    adapterId: entry.id,
    city: entry.defaultCity,
    listingType: entry.defaultListingType,
    maxResults: entry.defaultMaxResults,
    country: entry.country,
    executionMode: entry.executionMode,
    workerPath: entry.workerPath,
    fetchStrategy: (entry.defaultConfig.fetchStrategy as SourceDraft['fetchStrategy']) ?? entry.workerStrategyHint,
    district: entry.defaultConfig.district ?? '',
    customSearchUrl: entry.defaultConfig.customSearchUrl ?? '',
    rssUrl: entry.defaultConfig.rssUrl ?? '',
    includeHouses: (entry.defaultConfig.includeHouses as SourceDraft['includeHouses']) ?? 'no',
    wgMode: (entry.defaultConfig.wgMode as SourceDraft['wgMode']) ?? 'rooms',
  };
}

export function getCatalogByMarket(market?: SourceMarket | 'ALL') {
  if (!market || market === 'ALL') return sourceCatalog;
  return sourceCatalog.filter((item) => item.market === market);
}

export const defaultSourceDrafts: SourceDraft[] = sourceCatalog.map((entry) => ({
  ...buildDraftFromCatalog(entry.id),
  name: `${entry.label} ${entry.defaultCity}`,
}));
