build:
  maxIssues: 0

complexity:
  LongMethod:
    active: true
    threshold: 120
  LongParameterList:
    active: true
    functionThreshold: 18
    constructorThreshold: 10
  TooManyFunctions:
    active: false

style:
  MagicNumber:
    active: false
  WildcardImport:
    active: false
