build:
  maxIssues: 0

complexity:
  CyclomaticComplexMethod:
    active: true
    threshold: 25
  LongMethod:
    active: true
    threshold: 160
  LongParameterList:
    active: true
    functionThreshold: 20
    constructorThreshold: 10
  TooManyFunctions:
    active: false

style:
  MagicNumber:
    active: false
  StringTemplate:
    active: false
  WildcardImport:
    active: false
